### ISSUE TITLE
Project roadmap?

### ISSUE THREAD

**Issue by Odie** [clojureverse/clojurians-log-app#33]
Howdy!

Could you outline a rough roadmap? Or maybe all the things that are yet to be implemented or fixed before you think this is “good enough” to go live with. It’ll help a lot in understand what kind of tasks should be prioritized.

**Comment by plexus** [comment]
I need to set up the automatic import of new logs, and migrate the logging script from the old to the new server. That's really the only thing blocking the go-live.

It's a bit delicate cause I want to prevent messages from being dropped during the migration. I might have to ask the clojurians people for a second API key to make that easier.

I'll try to make time for this in the coming days. As far as the app is concerned I think it's already a big improvement over what we have. The issues here are a good overview of the backlog. Once the functionality is all there we can focus on performance, adding more tests, and in general making this a good example code base. 

It'll be interesting to see how it performs under load, but I'm willing to flip it over and see what happens. Cloudflare caching is set up so that should shield us a bit. I also need to better figure out how to tweak Datomic memory usage, as I get the impression the peer is using less memory than it could.

**Comment by plexus** [comment]
To give an update, I've added ansible scripts to set up the logging, so the main server that hosts the app is now also receiving messages from slack. It's not yet importing them automatically, for that there will have to be some logic for merging multiple log directories, and that's not there yet, but I've imported everything up to yesterday.

I also switched over the DNS, so we're live on clojurians-log.clojureverse.org now. :tada: .

I was hoping to also have the automatic import working today, but that'll have to wait. At least we're up to date again for now, so I won't get friendly messages every few days asking me if I'm aware that the log isn't updating :|

Things are slow, but we'll deal with that in due time. I've bumped the caching time up to 1 week, so I expect cloudflare to soon be able to take over a lot of our load.

**Comment by Odie** [comment]
Yikes, fetching https://clojurians-log.clojureverse.org/clojure/2015-07-01 took ~9.5s.

Would like to be able to track down the perf issue. What kind of AWS instance is it running on right now? Maybe I can replicate the production server and poke around to see what's going on.

**Comment by plexus** [comment]
That's only on first load, try again and it'll be much faster. Cache times
are set to 1 week, and cloudflare is set to cache everything,  so as people
browse the site more and more will get cached.

It's a free service, and things are in transition now, people will have to
have a little patience, we'll make this better one bit at a time.

I'm gonna be off the grid until some time next week, that's why I pushed a
bit to get this shipped today. My main priority after that will still be
the auto import and archiving of the log files, because that's
infrastructural stuff that needs to be out of the way, once that's done the
rest is just improving the app itself, which is easier to iterate and
collaborate on.
